<?php

namespace Database\Seeders;

use App\Models\Inventory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class InventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Inventory::insert([
            [
                'category_id' => 1,
                'name' => 'Piston',
                'code' => 'MSN0001',
                'price' => 500000,
                'desc' => 'Piston adalah komponen mesin yang berfungsi untuk mengubah energi panas menjadi energi mekanik',
                'stock' => 10,
            ],
            [
                'category_id' => 1,
                'name' => 'Silinder',
                'code' => 'MSN0002',
                'price' => 750000,
                'desc' => 'Silinder adalah tempat piston bergerak bolak-balik',
                'stock' => 15,
            ],
            [
                'category_id' => 1,
                'name' => 'Bearing',
                'code' => 'MSN0003',
                'price' => 300000,
                'desc' => 'Bearing adalah bantalan yang memungkinkan gerakan rotasi yang halus',
                'stock' => 20,
            ],
            [
                'category_id' => 1,
                'name' => 'Gasket',
                'code' => 'MSN0004',
                'price' => 100000,
                'desc' => 'Gasket adalah material yang digunakan untuk mencegah kebocoran antara dua permukaan',
                'stock' => 50,
            ],
            [
                'category_id' => 1,
                'name' => 'Seal',
                'code' => 'MSN0005',
                'price' => 50000,
                'desc' => 'Seal adalah komponen yang digunakan untuk mencegah kebocoran fluida',
                'stock' => 30,
            ],
            [
                'category_id' => 2,
                'name' => 'Sensor',
                'code' => 'ELK0001',
                'price' => 150000,
                'desc' => 'Sensor adalah perangkat yang mendeteksi perubahan fisik atau kimia di lingkungan',
                'stock' => 40,
            ],
            [
                'category_id' => 2,
                'name' => 'Sakelar',
                'code' => 'ELK0002',
                'price' => 25000,
                'desc' => 'Sakelar adalah perangkat yang digunakan untuk menghubungkan atau memutuskan aliran listrik',
                'stock' => 100,
            ],
            [
                'category_id' => 2,
                'name' => 'Kabel dan konektor',
                'code' => 'ELK0003',
                'price' => 50000,
                'desc' => 'Kabel dan konektor adalah komponen yang digunakan untuk menghubungkan perangkat elektronik',
                'stock' => 200,
            ],
            [
                'category_id' => 2,
                'name' => 'Relay',
                'code' => 'ELK0004',
                'price' => 100000,
                'desc' => 'Relay adalah sakelar elektromekanis yang dioperasikan oleh arus listrik',
                'stock' => 70,
            ],
            [
                'category_id' => 2,
                'name' => 'PCB',
                'code' => 'ELK0005',
                'price' => 200000,
                'desc' => 'PCB adalah papan sirkuit cetak yang digunakan untuk menghubungkan komponen elektronik',
                'stock' => 50,
            ],
            [
                'category_id' => 3,
                'name' => 'Rem cakram',
                'code' => 'PNR0001',
                'price' => 300000,
                'desc' => 'Rem cakram adalah sistem pengereman yang menggunakan cakram dan kaliper untuk menghentikan kendaraan',
                'stock' => 25,
            ],
            [
                'category_id' => 3,
                'name' => 'Kampas rem',
                'code' => 'PNR0002',
                'price' => 150000,
                'desc' => 'Kampas rem adalah komponen yang menekan cakram rem untuk memperlambat atau menghentikan kendaraan',
                'stock' => 100,
            ],
            [
                'category_id' => 3,
                'name' => 'Kaliper',
                'code' => 'PNR0003',
                'price' => 400000,
                'desc' => 'Kaliper adalah komponen yang menekan kampas rem ke cakram rem',
                'stock' => 30,
            ],
            [
                'category_id' => 3,
                'name' => 'Silinder rem',
                'code' => 'PNR0004',
                'price' => 200000,
                'desc' => 'Silinder rem adalah komponen yang mengubah tekanan hidrolik menjadi tekanan mekanik pada kampas rem',
                'stock' => 20,
            ],
            [
                'category_id' => 3,
                'name' => 'Minyak rem',
                'code' => 'PNR0005',
                'price' => 50000,
                'desc' => 'Minyak rem adalah fluida yang digunakan dalam sistem pengereman hidrolik',
                'stock' => 150,
            ],
            [
                'category_id' => 4,
                'name' => 'Radiator',
                'code' => 'PND0001',
                'price' => 800000,
                'desc' => 'Radiator adalah komponen yang digunakan untuk mendinginkan mesin',
                'stock' => 10,
            ],
            [
                'category_id' => 4,
                'name' => 'Kipas pendingin',
                'code' => 'PND0002',
                'price' => 200000,
                'desc' => 'Kipas pendingin adalah komponen yang membantu sirkulasi udara untuk mendinginkan radiator',
                'stock' => 25,
            ],
            [
                'category_id' => 4,
                'name' => 'Pompa air',
                'code' => 'PND0003',
                'price' => 500000,
                'desc' => 'Pompa air adalah komponen yang mengalirkan cairan pendingin melalui mesin',
                'stock' => 15,
            ],
            [
                'category_id' => 4,
                'name' => 'Termostat',
                'code' => 'PND0004',
                'price' => 100000,
                'desc' => 'Termostat adalah komponen yang mengatur aliran cairan pendingin berdasarkan suhu mesin',
                'stock' => 40,
            ],
            [
                'category_id' => 4,
                'name' => 'Selang radiator',
                'code' => 'PND0005',
                'price' => 50000,
                'desc' => 'Selang radiator adalah saluran fleksibel untuk mengalirkan cairan pendingin antara mesin dan radiator',
                'stock' => 50,
            ],
            [
                'category_id' => 5,
                'name' => 'Filter bahan bakar',
                'code' => 'BBK0001',
                'price' => 50000,
                'desc' => 'Filter bahan bakar adalah komponen yang menyaring kotoran dari bahan bakar sebelum masuk ke mesin',
                'stock' => 100,
            ],
            [
                'category_id' => 5,
                'name' => 'Pompa bahan bakar',
                'code' => 'BBK0002',
                'price' => 300000,
                'desc' => 'Pompa bahan bakar adalah komponen yang memompa bahan bakar dari tangki ke mesin',
                'stock' => 20,
            ],
            [
                'category_id' => 5,
                'name' => 'Injektor',
                'code' => 'BBK0003',
                'price' => 250000,
                'desc' => 'Injektor adalah komponen yang menyemprotkan bahan bakar ke dalam ruang bakar mesin',
                'stock' => 30,
            ],
            [
                'category_id' => 5,
                'name' => 'Karburator',
                'code' => 'BBK0004',
                'price' => 400000,
                'desc' => 'Karburator adalah komponen yang mencampur udara dan bahan bakar dalam proporsi yang tepat untuk pembakaran',
                'stock' => 10,
            ],
            [
                'category_id' => 5,
                'name' => 'Tangki bahan bakar',
                'code' => 'BBK0005',
                'price' => 700000,
                'desc' => 'Tangki bahan bakar adalah tempat penyimpanan bahan bakar kendaraan',
                'stock' => 5,
            ],
            [
                'category_id' => 6,
                'name' => 'Kopling',
                'code' => 'TRN0001',
                'price' => 500000,
                'desc' => 'Kopling adalah komponen yang menghubungkan dan memutuskan tenaga dari mesin ke transmisi',
                'stock' => 15,
            ],
            [
                'category_id' => 6,
                'name' => 'Gearbox',
                'code' => 'TRN0002',
                'price' => 1200000,
                'desc' => 'Gearbox adalah komponen yang mengatur kecepatan dan torsi kendaraan',
                'stock' => 8,
            ],
            [
                'category_id' => 6,
                'name' => 'Transmisi otomatis',
                'code' => 'TRN0003',
                'price' => 1500000,
                'desc' => 'Transmisi otomatis adalah sistem transmisi yang secara otomatis mengubah gigi kendaraan',
                'stock' => 4,
            ],
            [
                'category_id' => 6,
                'name' => 'Kabel kopling',
                'code' => 'TRN0004',
                'price' => 150000,
                'desc' => 'Kabel kopling adalah komponen yang menghubungkan pedal kopling ke mekanisme kopling',
                'stock' => 25,
            ],
            [
                'category_id' => 6,
                'name' => 'Shift solenoids',
                'code' => 'TRN0005',
                'price' => 300000,
                'desc' => 'Shift solenoids adalah komponen yang mengatur perpindahan gigi pada transmisi otomatis',
                'stock' => 10,
            ]
        ]);
    }
}
