<?php

namespace Database\Seeders;

use App\Models\Mobil;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MobilSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cars = [
            [
                'agen_id' => 1,
                'merk_id' => 1,
                'jenis_id' => 1,
                'transmisi_id' => 1,
                'warna_id' => 1,
                'cc_id' => 1,
                'tipe_id' => 2,
                'nama' => 'Avanza',
                'plat_nomor' => 'B 1234 ABC',
                'tahun' => '2019',
                'harga' => 50000,
                'kapasitas' => 8,
                'foto' => null,
            ],
            [
                'agen_id' => 1,
                'merk_id' => 2,
                'jenis_id' => 2,
                'transmisi_id' => 2,
                'warna_id' => 2,
                'cc_id' => 2,
                'tipe_id' => 2,
                'nama' => 'Xenia',
                'plat_nomor' => 'B 1411 AG',
                'tahun' => '2018',
                'harga' => 70000,
                'kapasitas' => 8,
                'foto' => null,
            ],
            [
                'agen_id' => 1,
                'merk_id' => 3,
                'jenis_id' => 1,
                'transmisi_id' => 2,
                'warna_id' => 3,
                'cc_id' => 3,
                'tipe_id' => 2,
                'nama' => 'Terios',
                'plat_nomor' => 'L 121 AB',
                'tahun' => '2022',
                'harga' => 100000,
                'kapasitas' => 6,
                'foto' => null,
            ],
            [
                'agen_id' => 1,
                'merk_id' => 4,
                'jenis_id' => 2,
                'transmisi_id' => 1,
                'warna_id' => 4,
                'cc_id' => 4,
                'tipe_id' => 1,
                'nama' => 'Ertiga',
                'plat_nomor' => 'B 1234 ABC',
                'tahun' => '2019',
                'harga' => 60000,
                'kapasitas' => 8,
                'foto' => null,
            ],
            [
                'agen_id' => 1,
                'merk_id' => 5,
                'jenis_id' => 1,
                'transmisi_id' => 2,
                'warna_id' => 5,
                'cc_id' => 5,
                'tipe_id' => 1,
                'nama' => 'Xpander',
                'plat_nomor' => 'B 6511 AG',
                'tahun' => '2018',
                'harga' => 120000,
                'kapasitas' => 8,
                'foto' => null,
            ],
            [
                'agen_id' => 2,
                'merk_id' => 6,
                'jenis_id' => 2,
                'transmisi_id' => 1,
                'warna_id' => 6,
                'cc_id' => 6,
                'tipe_id' => 1,
                'nama' => 'Livina',
                'plat_nomor' => 'L 7454 AB',
                'tahun' => '2022',
                'harga' => 100000,
                'kapasitas' => 6,
                'foto' => null,
            ],
            [
                'agen_id' => 2,
                'merk_id' => 7,
                'jenis_id' => 1,
                'transmisi_id' => 2,
                'warna_id' => 7,
                'cc_id' => 7,
                'tipe_id' => 2,
                'nama' => 'Mobilio',
                'plat_nomor' => 'B 1255 ABC',
                'tahun' => '2019',
                'harga' => 80000,
                'kapasitas' => 8,
                'foto' => null,
            ],
            [
                'agen_id' => 2,
                'merk_id' => 8,
                'jenis_id' => 2,
                'transmisi_id' => 1,
                'warna_id' => 8,
                'cc_id' => 8,
                'tipe_id' => 2,
                'nama' => 'BRV',
                'plat_nomor' => 'B 1411 AG',
                'tahun' => '2018',
                'harga' => 70000,
                'kapasitas' => 8,
                'foto' => null,
            ],
            [
                'agen_id' => 2,
                'merk_id' => 9,
                'jenis_id' => 1,
                'transmisi_id' => 2,
                'warna_id' => 9,
                'cc_id' => 9,
                'tipe_id' => 2,
                'nama' => 'Rush',
                'plat_nomor' => 'L 2132 AB',
                'tahun' => '2022',
                'harga' => 100000,
                'kapasitas' => 6,
                'foto' => null,
            ],
            [
                'agen_id' => 3,
                'merk_id' => 1,
                'jenis_id' => 2,
                'transmisi_id' => 1,
                'warna_id' => 1,
                'cc_id' => 1,
                'tipe_id' => 1,
                'nama' => 'Grand Livina',
                'plat_nomor' => 'B 1212 BG',
                'tahun' => '2019',
                'harga' => 50000,
                'kapasitas' => 8,
                'foto' => null,
            ],
            [
                'agen_id' => 3,
                'merk_id' => 2,
                'jenis_id' => 1,
                'transmisi_id' => 2,
                'warna_id' => 2,
                'cc_id' => 2,
                'tipe_id' => 1,
                'nama' => 'Grand Xenia',
                'plat_nomor' => 'B 1411 AG',
                'tahun' => '2018',
                'harga' => 70000,
                'kapasitas' => 8,
                'foto' => null,
            ],
            [
                'agen_id' => 3,
                'merk_id' => 3,
                'jenis_id' => 2,
                'transmisi_id' => 1,
                'warna_id' => 3,
                'cc_id' => 3,
                'tipe_id' => 2,
                'nama' => 'Terios',
                'plat_nomor' => 'L 121 AB',
                'tahun' => '2022',
                'harga' => 100000,
                'kapasitas' => 6,
                'foto' => null,
            ],
            [
                'agen_id' => 3,
                'merk_id' => 4,
                'jenis_id' => 1,
                'transmisi_id' => 2,
                'warna_id' => 4,
                'cc_id' => 4,
                'tipe_id' => 2,
                'nama' => 'Ertiga',
                'plat_nomor' => 'B 1234 ABC',
                'tahun' => '2019',
                'harga' => 60000,
                'kapasitas' => 8,
                'foto' => null,
            ],
            [
                'agen_id' => 3,
                'merk_id' => 5,
                'jenis_id' => 2,
                'transmisi_id' => 1,
                'warna_id' => 5,
                'cc_id' => 5,
                'tipe_id' => 1,
                'nama' => 'Xpander',
                'plat_nomor' => 'B 6511 AG',
                'tahun' => '2018',
                'harga' => 120000,
                'kapasitas' => 8,
                'foto' => null,
            ],
        ];

        foreach ($cars as $car) {
            Mobil::create($car);
        }
    }
}
